// Generated by uniffi-bindgen-react-native
package com.ariel

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder

@ReactModule(name = ArielModule.NAME)
class ArielModule(reactContext: ReactApplicationContext) :
  NativeArielSpec(reactContext) {

  override fun getName(): String {
    return NAME
  }

  // Two native methods implemented in cpp-adapter.cpp, and ultimately
  // react-native-ariel.cpp

  external fun nativeInstallRustCrate(runtimePointer: Long, callInvoker: CallInvokerHolder): Boolean
  external fun nativeCleanupRustCrate(runtimePointer: Long): Boolean

  override fun installRustCrate(): Boolean {
    val context = this.reactApplicationContext
    return nativeInstallRustCrate(
      context.javaScriptContextHolder!!.get(),
      resolveCallInvokerHolder(context)
    )
  }

  private fun resolveCallInvokerHolder(context: ReactApplicationContext): CallInvokerHolder {
    // RN 0.74+ exposes getJSCallInvokerHolder() on ReactContext directly.
    // RN 0.73 only has it on CatalystInstance — use reflection to handle both.
    val direct = context.javaClass.methods.firstOrNull { it.name == "getJSCallInvokerHolder" }
    if (direct != null) return direct.invoke(context) as CallInvokerHolder
    @Suppress("DEPRECATION")
    val ci = checkNotNull(context.catalystInstance) { "No CatalystInstance" }
    return ci.javaClass.methods.first { it.name == "getJSCallInvokerHolder" }.invoke(ci) as CallInvokerHolder
  }

  override fun cleanupRustCrate(): Boolean {
    return nativeCleanupRustCrate(
      this.reactApplicationContext.javaScriptContextHolder!!.get()
    )
  }

  companion object {
    const val NAME = "Ariel"

    init {
      System.loadLibrary("react-native-ariel")
    }
  }
}