// Generated by uniffi-bindgen-react-native
// Export the generated bindings to the app.
export * from './generated/web/mermaid_wrapper';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as mermaid_wrapper from './generated/web/mermaid_wrapper';

import initAsync from './generated/web/wasm-bindgen/react_native_ariel_rs.js';
import wasmPath from './generated/web/wasm-bindgen/react_native_ariel_rs_bg.wasm';

export async function uniffiInitAsync() {
  await initAsync({ module_or_path: wasmPath })

  // Initialize the generated bindings: mostly checksums, but also callbacks.
  // - the boolean flag ensures this loads exactly once, even if the JS code
  //   is reloaded (e.g. during development with metro).
  mermaid_wrapper.default.initialize();
}

// Export the crates as individually namespaced objects.
export default {
  mermaid_wrapper,
};


export { useArielTheme } from './useArielTheme.web';